### ISSUE TITLE
Falsely claims I am winning.

### ISSUE THREAD

**Issue by rossjones** [maxf/address-matcher#1]
Went to site, chose a username (Rob) and went through the process of matching 5 addresses. At the end I saw:  

<img width="447" alt="gov_uk_-_the_best_place_to_find_government_services_and_information" src="https://cloud.githubusercontent.com/assets/118063/19315142/7f20c6a0-9094-11e6-96c6-cc8bad41039f.png">

First place! I rock.

Now imagine my disappointment when I click on Scores and find out I'm not actually in first place.

<img width="926" alt="gov_uk_-_the_best_place_to_find_government_services_and_information" src="https://cloud.githubusercontent.com/assets/118063/19315167/96d07de0-9094-11e6-9724-4b48f2fc1c8c.png">

**Comment by maxf** [comment]
Was all fake. Now removed
